/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/chicken/': RouteRecordInfo<'/chicken/', '/chicken', Record<never, never>, Record<never, never>>,
    '/chicken/process': RouteRecordInfo<'/chicken/process', '/chicken/process', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/fish/': RouteRecordInfo<'/fish/', '/fish', Record<never, never>, Record<never, never>>,
    '/fish/process': RouteRecordInfo<'/fish/process', '/fish/process', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/oil/': RouteRecordInfo<'/oil/', '/oil', Record<never, never>, Record<never, never>>,
    '/oil/1/': RouteRecordInfo<'/oil/1/', '/oil/1', Record<never, never>, Record<never, never>>,
    '/oil/1/process': RouteRecordInfo<'/oil/1/process', '/oil/1/process', Record<never, never>, Record<never, never>>,
    '/oil/2/': RouteRecordInfo<'/oil/2/', '/oil/2', Record<never, never>, Record<never, never>>,
    '/oil/2/process': RouteRecordInfo<'/oil/2/process', '/oil/2/process', Record<never, never>, Record<never, never>>,
    '/oil/3/': RouteRecordInfo<'/oil/3/', '/oil/3', Record<never, never>, Record<never, never>>,
    '/oil/3/process': RouteRecordInfo<'/oil/3/process', '/oil/3/process', Record<never, never>, Record<never, never>>,
    '/oil/4/': RouteRecordInfo<'/oil/4/', '/oil/4', Record<never, never>, Record<never, never>>,
    '/oil/4/process': RouteRecordInfo<'/oil/4/process', '/oil/4/process', Record<never, never>, Record<never, never>>,
    '/oil/process': RouteRecordInfo<'/oil/process', '/oil/process', Record<never, never>, Record<never, never>>,
    '/pork/': RouteRecordInfo<'/pork/', '/pork', Record<never, never>, Record<never, never>>,
    '/pork/process': RouteRecordInfo<'/pork/process', '/pork/process', Record<never, never>, Record<never, never>>,
    '/products': RouteRecordInfo<'/products', '/products', Record<never, never>, Record<never, never>>,
    '/raw-material': RouteRecordInfo<'/raw-material', '/raw-material', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/rice/': RouteRecordInfo<'/rice/', '/rice', Record<never, never>, Record<never, never>>,
    '/rice/process': RouteRecordInfo<'/rice/process', '/rice/process', Record<never, never>, Record<never, never>>,
    '/search': RouteRecordInfo<'/search', '/search', Record<never, never>, Record<never, never>>,
    '/shrimp/': RouteRecordInfo<'/shrimp/', '/shrimp', Record<never, never>, Record<never, never>>,
    '/shrimp/process': RouteRecordInfo<'/shrimp/process', '/shrimp/process', Record<never, never>, Record<never, never>>,
    '/sys': RouteRecordInfo<'/sys', '/sys', Record<never, never>, Record<never, never>>,
    '/sys/': RouteRecordInfo<'/sys/', '/sys', Record<never, never>, Record<never, never>>,
    '/sys/product': RouteRecordInfo<'/sys/product', '/sys/product', Record<never, never>, Record<never, never>>,
    '/sys/purchase': RouteRecordInfo<'/sys/purchase', '/sys/purchase', Record<never, never>, Record<never, never>>,
  }
}
