import { Category } from './types'

export interface Product {
  id: number
  name: string
  category: Category
  price: number
  unit: string
  image: string
  testReport: string
}

export const products: Product[] = [
  {
    id: 1,
    name: '福禄花鲜香压榨菜籽油5L',
    category: Category.OIL,
    price: 159.8,
    unit: '桶',
    image: '/reports/福禄花鲜香压榨菜籽油5L/福禄花鲜香压榨菜籽油5L.webp',
    testReport: '/reports/福禄花鲜香压榨菜籽油5L/产品检测报告.pdf',
  },
  {
    id: 2,
    name: '福禄花鲜香压榨玉米油5L',
    category: Category.OIL,
    price: 112,
    unit: '桶',
    image: '/reports/福禄花鲜香压榨玉米油5L/福禄花鲜香压榨玉米油5L.jpeg',
    testReport: '/reports/福禄花鲜香压榨玉米油5L/产品检测报告.pdf',
  },
  {
    id: 3,
    name: '福禄花压榨葵花籽油10L',
    category: Category.OIL,
    price: 215,
    unit: '桶',
    image: '/reports/福禄花压榨葵花籽油10L/福禄花压榨葵花籽油10L.jpeg',
    testReport: '/reports/福禄花压榨葵花籽油10L/产品检测报告.pdf',
  },
  {
    id: 4,
    name: '福禄花压榨花生油10L',
    category: Category.OIL,
    price: 180,
    unit: '桶',
    image: '/reports/福禄花压榨花生油10L/福禄花压榨花生油10L.jpeg',
    testReport: '/reports/福禄花压榨花生油10L/产品检测报告.pdf',
  },
  {
    id: 5,
    name: '玲珑心压榨玉米油5L',
    category: Category.OIL,
    price: 120,
    unit: '桶',
    image: '/reports/玲珑心压榨玉米油5L/玲珑心压榨玉米油5L.jpeg',
    testReport: '/reports/玲珑心压榨玉米油5L/产品检测报告.pdf',
  },
  {
    id: 6,
    name: '福禄花玉米油5L',
    category: Category.OIL,
    price: 120,
    unit: '桶',
    image: '/reports/福禄花玉米油5L/福禄花玉米油5L.jpg',
    testReport: '/reports/福禄花玉米油5L/产品检测报告.pdf',
  },
  {
    id: 7,
    name: '玲珑心玉米油5L',
    category: Category.OIL,
    price: 120,
    unit: '桶',
    image: '/reports/玲珑心玉米油5L/玲珑心玉米油5L.jpg',
    testReport: '/reports/玲珑心玉米油5L/产品检测报告.pdf',
  },
  {
    id: 8,
    name: '西王纯香压榨菜籽油5L（中百、特渠）',
    category: Category.OIL,
    price: 130,
    unit: '桶',
    image: '/reports/西王纯香压榨菜籽油5L（中百、特渠）/西王纯香压榨菜籽油5L（中百、特渠）.jpg',
    testReport: '/reports/西王纯香压榨菜籽油5L（中百、特渠）/产品检测报告.pdf',
  },
  {
    id: 9,
    name: '西王低芥酸浓香菜籽油5L',
    category: Category.OIL,
    price: 109,
    unit: '桶',
    image: '/reports/西王低芥酸浓香菜籽油5L/西王低芥酸浓香菜籽油5L.jpg',
    testReport: '/reports/西王低芥酸浓香菜籽油5L/产品检测报告.pdf',
  },
  {
    id: 10,
    name: '西王好鲜生玉米胚芽油5L',
    category: Category.OIL,
    price: 110,
    unit: '桶',
    image: '/reports/西王好鲜生玉米胚芽油5L/西王好鲜生玉米胚芽油5L.jpg',
    testReport: '/reports/西王好鲜生玉米胚芽油5L/产品检测报告.pdf',
  },
  {
    id: 11,
    name: '西王经典玉米胚芽油5L',
    category: Category.OIL,
    price: 189.9,
    unit: '桶',
    image: '/reports/西王经典玉米胚芽油5L/西王经典玉米胚芽油5L.jpg',
    testReport: '/reports/西王经典玉米胚芽油5L/产品检测报告.pdf',
  },
  {
    id: 12,
    name: '西王葵花籽油5L（优选）',
    category: Category.OIL,
    price: 108.69,
    unit: '桶',
    image: '/reports/西王葵花籽油5L（优选）/西王葵花籽油5L（优选）.avif',
    testReport: '/reports/西王葵花籽油5L（优选）/产品检测报告.pdf',
  },
  {
    id: 13,
    name: '西王食用植物调和油5L（玉橄）',
    category: Category.OIL,
    price: 148,
    unit: '桶',
    image: '/reports/西王食用植物调和油5L（玉橄）/西王食用植物调和油5L（玉橄）.avif',
    testReport: '/reports/西王食用植物调和油5L（玉橄）/产品检测报告.pdf',
  },
  {
    id: 14,
    name: '西王小榨原香菜籽油5L',
    category: Category.OIL,
    price: 116.6,
    unit: '桶',
    image: '/reports/西王小榨原香菜籽油5L/西王小榨原香菜籽油5L.jpeg',
    testReport: '/reports/西王小榨原香菜籽油5L/产品检测报告.pdf',
  },
  {
    id: 15,
    name: '西王小榨甄香菜籽油5L',
    category: Category.OIL,
    price: 99.9,
    unit: '桶',
    image: '/reports/西王小榨甄香菜籽油5L/西王小榨甄香菜籽油5L.jpeg',
    testReport: '/reports/西王小榨甄香菜籽油5L/产品检测报告.pdf',
  },
  {
    id: 16,
    name: '西王压榨菜籽油5L',
    category: Category.OIL,
    price: 99.9,
    unit: '桶',
    image: '/reports/西王压榨菜籽油5L/西王压榨菜籽油5L.jpeg',
    testReport: '/reports/西王压榨菜籽油5L/产品检测报告.pdf',
  },
  {
    id: 17,
    name: '西王压榨花生油5L',
    category: Category.OIL,
    price: 99.9,
    unit: '桶',
    image: '/reports/西王压榨花生油5L/西王压榨花生油5L.jpeg',
    testReport: '/reports/西王压榨花生油5L/产品检测报告.pdf',
  },
  {
    id: 18,
    name: '西王压榨葵花籽油5.27L（惠 悦味上品）',
    category: Category.OIL,
    price: 67.9,
    unit: '桶',
    image: '/reports/西王压榨葵花籽油5.27L（惠 悦味上品）/西王压榨葵花籽油5.27L（惠 悦味上品）.jpg',
    testReport: '/reports/西王压榨葵花籽油5.27L（惠 悦味上品）/产品检测报告.pdf',
  },
  {
    id: 19,
    name: '西王压榨葵花籽油5L',
    category: Category.OIL,
    price: 99.9,
    unit: '桶',
    image: '/reports/西王压榨葵花籽油5L/西王压榨葵花籽油5L.jpg',
    testReport: '/reports/西王压榨葵花籽油5L/产品检测报告.pdf',
  },
  {
    id: 20,
    name: '西王压榨玉米油5L',
    category: Category.OIL,
    price: 149,
    unit: '桶',
    image: '/reports/西王压榨玉米油5L/西王压榨玉米油5L.avif',
    testReport: '/reports/西王压榨玉米油5L/产品检测报告.pdf',
  },
  {
    id: 21,
    name: '西王油酸多黑花生油5L',
    category: Category.OIL,
    price: 550,
    unit: '桶',
    image: '/reports/西王油酸多黑花生油5L/西王油酸多黑花生油5L.jpg',
    testReport: '/reports/西王油酸多黑花生油5L/产品检测报告.pdf',
  },
  {
    id: 22,
    name: '西王玉米胚芽油5.27L（惠 悦味上品）',
    category: Category.OIL,
    price: 37.9,
    unit: '桶',
    image: '/reports/西王玉米胚芽油5.27L（惠 悦味上品）/西王玉米胚芽油5.27L（惠 悦味上品）.jpg',
    testReport: '/reports/西王玉米胚芽油5.27L（惠 悦味上品）/产品检测报告.pdf',
  },
  {
    id: 23,
    name: '西王玉米胚芽油5L（零反式脂肪）',
    category: Category.OIL,
    price: 99.9,
    unit: '桶',
    image: '/reports/西王玉米胚芽油5L（零反式脂肪）/西王玉米胚芽油5L（零反式脂肪）.avif',
    testReport: '/reports/西王玉米胚芽油5L（零反式脂肪）/产品检测报告.pdf',
  },
  {
    id: 24,
    name: '西王玉米胚芽油5L（普胚）',
    category: Category.OIL,
    price: 89.9,
    unit: '桶',
    image: '/reports/西王玉米胚芽油5L（普胚）/西王玉米胚芽油5L（普胚）.avif',
    testReport: '/reports/西王玉米胚芽油5L（普胚）/产品检测报告.pdf',
  },
  {
    id: 25,
    name: '西王玉米胚芽油鲜胚5L',
    category: Category.OIL,
    price: 99.9,
    unit: '桶',
    image: '/reports/西王玉米胚芽油鲜胚5L/西王玉米胚芽油鲜胚5L.avif',
    testReport: '/reports/西王玉米胚芽油鲜胚5L/产品检测报告.pdf',
  },
  {
    id: 26,
    name: '西王玉米油5L（尊享、优选）',
    category: Category.OIL,
    price: 199.9,
    unit: '桶',
    image: '/reports/西王玉米油5L（尊享、优选）/西王玉米油5L（尊享、优选）.avif',
    testReport: '/reports/西王玉米油5L（尊享、优选）/产品检测报告.pdf',
  },
]
